image: docker:latest
stages:
  - build
  - release

variables:
  TEST_IMAGE: 183321040270.dkr.ecr.eu-central-1.amazonaws.com/covod-web-app:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: 183321040270.dkr.ecr.eu-central-1.amazonaws.com/covod-web-app:latest

before_script:
  - docker login -u AWS -p $REGISTRY_TOKEN 183321040270.dkr.ecr.eu-central-1.amazonaws.com

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE --build-arg REACT_APP_API_BASE_URL=$API_BASE_URL --build-arg REACT_APP_CLIENT_ID=$CLIENT_ID --build-arg REACT_APP_CLIENT_SECRET=$CLIENT_SECRET .
    - docker push $TEST_IMAGE

# Testing pipeline goes here

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
  trigger:
    - cau-vs-virus/covod-web-app
